import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "AtlasiaAI",
        Title: data.title,
        Creator: "AtlasiaAI"
      }
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);

    // TITLE


    doc
      .fontSize(28)
      .fillColor("#11827D")
      .text(data.title, {
        align: "center"
      });

    // SUBTITLE


    if (data.subtitle) {
      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .fillColor("#6B7280")
        .text(data.subtitle, {
          align: "center"
        });

      doc.moveDown(2);
    }


    // SECTIONS
 

    data?.sections?.forEach((s) => {
      doc
        .fontSize(18)
        .fillColor("#111827")
        .text(s.heading);

      doc.moveDown(0.5);

      s?.points?.forEach((p) => {
        doc
          .fontSize(11)
          .fillColor("#374151")
          .text("• " + p, {
            lineGap: 5
          });

        doc.moveDown();
      });

      doc.moveDown();
    });

    // FOOTER

    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text("Generated By Atlasia AI", {
        align: "center"
      });

    // end
    doc.end();
  });
};