import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  secondary: "0F172A",
  text: "334155",
  light: "F8FAFC",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
  accent: "60A5FA",
};

export const generatePpt = async (data)=>{

    let ppt = new pptxgen();
    ppt.layout="LAYOUT_WIDE"
    ppt.author="AtlasiaAI"
    ppt.title=data.title
    ppt.subject=data.title
    ppt.company="AtlasiaAI"
    ppt.lang="en-US"
    ppt.theme={
            headFontFace:"Aptos",
            bodyFontFace:"Aptos",
            lang:"en-US"
    }
    
     const addCover =(data)=>{
        const slide = ppt.addSlide()
        slide.background={
            color:COLORS.primary
        }

        //top accent bar
        slide.addShape(ppt.ShapeType.rect, {
         x: 0, y: 0, w: 13.33, h: 0.18,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });

        //bottom accent bar — top se match karte hue, slide ko visually balance karta hai
        slide.addShape(ppt.ShapeType.rect, {
         x: 0, y: 7.32, w: 13.33, h: 0.18,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });

        //chhota "PRESENTATION" badge, title ke upar
        slide.addShape(ppt.ShapeType.roundRect, {
         x: 5.92, y: 2.0, w: 1.5, h: 0.36,
         fill: { color: "1D4ED8" },
         line: { color: COLORS.accent, width: 1 },
         radius: 0.18
        })
        slide.addText("PRESENTATION",{
         x: 5.92, y: 2.0, w: 1.5, h: 0.36,
         align:"center", valign:"middle",
         color:COLORS.white,
         bold:true,
         fontSize:9,
         charSpacing:2
        })

        //title ab slide ke center me hai, accent bar se overlap nahi karta
        slide.addText(data.title,{
         x: 0.7,
         y: 2.6,
         w: 12,
         h: 1.1,
         align:"center",
         valign:"middle",
         color:COLORS.white,
         bold:true,
         fontSize:34
        })

        //title ke neeche chhoti underline accent
        slide.addShape(ppt.ShapeType.rect, {
         x: 5.67, y: 3.8, w: 2, h: 0.035,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });

         slide.addText(data.subtitle,{
         x: 1,
         y: 4.05,
         w: 11.5,
         h: 0.5,
         align:"center",
         valign:"middle",
         color:"DBEAFE",
         fontSize:16

        })

         slide.addText("Generated By Atlasia AI",{
         x: 0,
         y: 6.9,
         w: 13.33,
         h: 0.2,
         align:"center",
         color:"BFDBFE",
         fontSize:10

        })


     }

    addCover(data)
    
    const addContentSlide = (ppt, title, points, page , total)=>{
        const slide = ppt.addSlide()
        slide.background={
            color:COLORS.white
        }

        slide.addText(title,{
         x: 0.6,
         y: 0.35,
         w: 10,
         h: 0.4,
         color:COLORS.primary,
         bold:true,
         fontSize:24

        })

        slide.addShape(ppt.ShapeType.line, {
         x: 0.6,
         y: 0.85,
         w: 12,
         h: 0,
         line: {
             color: COLORS.border,
             width:1.2
         }
        });

        const visiblePoints = points.slice(0,6) //bas 6 points hi show karenge
        visiblePoints.forEach((point, index)=>{
            const y = 1.2 + index*0.75
         slide.addShape(ppt.ShapeType.roundRect, {
         x: 0.7,
         y,
         w: 12,
         h: 0.58,
         fill : {
            color: index%2 ? "F8FAFC": "EFF6FF"
         },
         line: {
             color: COLORS.border,
         },
         radius : 0.08
        })

        slide.addShape(ppt.ShapeType.roundRect, {
         x: 0.92,
         y:y+0.18,
         w: 0.12,
         h: 0.12,
         fill : {
            color: COLORS.primary
         },
         line: {
             color: COLORS.primary,
         },
        })

        slide.addText(point,{
         x: 1.2,
         y: y+0.08,
         w: 11,
         h: 0.35,
         color:COLORS.text,
         fit:"shrink",
         fontSize:15

        })
          
        slide.addText(`${page}/${total}`,{
         x: 12.1,
         y: 6.9,
         w: 0.8,
         h: 0.2,
         color:COLORS.muted,
         align:"right",
         fontSize:10

        })

        slide.addText(`Atlasia AI`,{
         x: 0.6,
         y: 6.9,
         w: 2,
         h: 0.2,
         color:COLORS.muted,
         fontSize:20
        })
            
        
        
        })


    }

    data?.slides?.forEach((s,i) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            i+1,
            data.slides.length
        )
    });


    const addThankYou=(ppt)=>{
       const slide = ppt.addSlide()

        slide.background={
            color:COLORS.primary
        }

        //cover se match karti accent bars, deck ko ek jaisa feel deti hain
        slide.addShape(ppt.ShapeType.rect, {
         x: 0, y: 0, w: 13.33, h: 0.18,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });
        slide.addShape(ppt.ShapeType.rect, {
         x: 0, y: 7.32, w: 13.33, h: 0.18,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });

        slide.addText(`Thank You`,{
         x: 0,
         y: 2.9,
         w: 13.33,
         h: 1,
         align:"center",
         valign:"middle",
         color:COLORS.white,
         fontSize:40,
         bold:true
        });

        //underline accent, cover ke title underline se match karta hua
        slide.addShape(ppt.ShapeType.rect, {
         x: 5.67, y: 4.05, w: 2, h: 0.035,
         fill: { color: COLORS.accent },
         line: { color: COLORS.accent }
        });

        slide.addText(`Questions & Discussion`,{
         x: 0,
         y: 4.25,
         w: 13.33,
         h: 0.5,
         align:"center",
         color:"DBEAFE",
         fontSize:16
        });

        slide.addText(`Generated by Atlasia AI`,{
         x: 0,
         y: 6.9,
         w: 13.33,
         h: 0.2,
         align:"center",
         color:"BFDBFE",
         fontSize:10,

        });

    }
    addThankYou(ppt);
    return ppt;

}